version: '3'

services:
  web:
    image: node:16.18.0
    ports:
      - 3000:3000
    volumes:
      - ./web/:/usr/src/app/web/
    tty: true
    init: true
    working_dir: /usr/src/app/web/
    command: npm run dev

  server:
    build:
      context: ./server
      target: dev
    volumes:
      - ./server:/usr/src/app/web/
    working_dir: /usr/src/app/web/
    ports:
      - 8000:8000
    
