name: Backend

on:
  push:
    branches: [ feature/* ]
    paths:
      - "**.py"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install mypy requests pytest flake8 fastapi pydantic fastapi.middleware.cors fastapi.testclient
      run: pip install mypy requests pytest flake8 fastapi pydantic fastapi.middleware.cors fastapi.testclient
    - name: Lint with flake8
      run: flake8 --max-line-length=120
    - name: Code Check with mypy
      run: mypy --strict .
    - name: Test with Pytest and Doctest
      run: |
        pytest .
        python -m doctest *.py
        
