name: Heroku backend deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_BACKEND_API_KEY}} #herokuのAPIのkey
          heroku_app_name: "yukusi-backend" #herokuアプリの名前
          heroku_email: "k218571@ie.u-ryukyu.ac.jp" #アカウントのメールアドレス
          appdir: "server" #サブディレクトリ名
