name: Heroku dev frontend deploy

on:
  push:
    branches:
      - 'feature/#45*' # dev環境にデプロイしたい際はこちらのブランチ番号を変更してください

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} #herokuのAPIのkey
          heroku_app_name: "yukusi-dev" #herokuアプリの名前
          heroku_email: "soto@cr.ie.u-ryukyu.ac.jp" #アカウントのメールアドレス
          appdir: "web" #サブディレクトリ名
