name: Lint

on:
  push:
    branches:
      - feature/add_linter_formatter_ci
    paths:
      - '*.py'

jobs:
  lint: # 任意のジョブ名
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics