name: Lint

on:
  push:
    branches:
      - master
      - feature/*
    paths:
      - '*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v
      - name: Set up Python
        uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'
        - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true