name: Lint

on:
  push:
    branches: [ feature/* ]
    paths:
      - "**.py"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install flake8
      run: pip install flake8
    - name: Lint with flake8
      run: |
        flake8 --max-line-length=120